version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/server"
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
      - "3035:3035"
    depends_on:
      - db
